main:
  version: '1.1.0'
  memchache_server: 'localhost:11211'
  db_url: 'sqlite:///db.sqlite'
  cache_dir: '.cache'

feed:
  credentials_file: 'credentials.json'
  photo_size:
    website: 122
    database: 144
